  services:
    backend:
      container_name: gofundbot
      build:
        context: .
      user: "${GOFUNDBOT_UID:-1000}:${GOFUNDBOT_GID:-1000}"
      env_file:
        - ./.env
      volumes:
        - ./Data:/app/Data
        - ./Data:/Data
      ports:
        - 5000:5000
      restart: unless-stopped

  volumes:
    db_data:


  networks:
    default:
      driver: bridge
